export type ExerciseTag = "Lower" | "Push" | "Pull" | "Core";

export interface Exercise {
  id: string;
  name: string;
  nameEs: string;
  category: "compound" | "multi_joint" | "isolation";
  muscleGroups: string[];
  equipment: string[];
  notes: string;
  notesEs: string;
  gifUrl: string | null;
  gifUrl2: string | null;
  instructions: string[];
  instructionsEs: string[];
  tags: ExerciseTag[];
}

export const EXERCISES: Exercise[] = [
  // Compound
  { id: "a0000000-0000-4000-8000-000000000001", name: "Dumbbell Goblet Squat", nameEs: "Sentadilla Goblet con Mancuerna", category: "compound", muscleGroups: ["quads", "glutes", "core"], equipment: ["dumbbell"], notes: "Hold dumbbell at chest level. Keep elbows inside knees.", notesEs: "Sostén la mancuerna a nivel del pecho. Mantén los codos dentro de las rodillas.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg", instructions: ["Stand holding a light kettlebell by the horns close to your chest. This will be your starting position.","Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight.","At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-000000000002", name: "Romanian Deadlift (DB)", nameEs: "Peso Muerto Rumano con Mancuernas", category: "compound", muscleGroups: ["hamstrings", "glutes", "lower_back"], equipment: ["dumbbell"], notes: "Hinge at hips, slight knee bend. Feel stretch in hamstrings.", notesEs: "Bisagra en las caderas, ligera flexión de rodillas. Siente el estiramiento en los isquiotibiales.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg", instructions: ["Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.","Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.","Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.","Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-000000000003", name: "Dumbbell Bench Press", nameEs: "Press de Banca con Mancuernas", category: "compound", muscleGroups: ["chest", "triceps", "shoulders"], equipment: ["dumbbell"], notes: "Flat bench. Control the eccentric.", notesEs: "Banco plano. Controla la fase excéntrica.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg", instructions: ["Lie down on a flat bench with a dumbbell in each hand resting on top of your thighs. The palms of your hands will be facing each other.","Then, using your thighs to help raise the dumbbells up, lift the dumbbells one at a time so that you can hold them in front of you at shoulder width.","Once at shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. The dumbbells should be just to the sides of your chest, with your upper arm and forearm creating a 90 degree angle. Be sure to maintain full control of the dumbbells at all times. This will be your starting position.","Then, as you breathe out, use your chest to push the dumbbells up. Lock your arms at the top of the lift and squeeze your chest, hold for a second and then begin coming down slowly. Tip: Ideally, lowering the weight should take about twice as long as raising it.","Repeat the movement for the prescribed amount of repetitions of your training program."], instructionsEs: [], tags: ["Push"] },
  { id: "a0000000-0000-4000-8000-000000000004", name: "Dumbbell Overhead Press", nameEs: "Press de Hombros con Mancuernas", category: "compound", muscleGroups: ["shoulders", "triceps", "core"], equipment: ["dumbbell"], notes: "Seated or standing. Brace core throughout.", notesEs: "Sentada o de pie. Mantén el core contraído.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/1.jpg", instructions: ["While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.","Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.","Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.","Now, exhale and push the dumbbells upward until they touch at the top.","Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Push"] },
  { id: "a0000000-0000-4000-8000-000000000005", name: "Dumbbell Bent-Over Row", nameEs: "Remo Inclinado con Mancuernas", category: "compound", muscleGroups: ["back", "biceps", "rear_delts"], equipment: ["dumbbell"], notes: "Hinge forward 45 degrees. Pull to hip.", notesEs: "Inclínate 45 grados. Tira hacia la cadera.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/1.jpg", instructions: ["With a dumbbell in each hand (palms facing your torso), bend your knees slightly and bring your torso forward by bending at the waist; as you bend make sure to keep your back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The weights should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.","While keeping the torso stationary, lift the dumbbells to your side (as you breathe out), keeping the elbows close to the body (do not exert any force with the forearm other than holding the weights). On the top contracted position, squeeze the back muscles and hold for a second.","Slowly lower the weight again to the starting position as you inhale.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Pull"] },
  { id: "a0000000-0000-4000-8000-000000000006", name: "Dumbbell Lunges", nameEs: "Zancadas con Mancuernas", category: "compound", muscleGroups: ["quads", "glutes", "hamstrings"], equipment: ["dumbbell"], notes: "Alternating or walking. Knee tracks over toe.", notesEs: "Alternando o caminando. La rodilla sigue la dirección del pie.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg", instructions: ["Stand with your torso upright holding two dumbbells in your hands by your sides. This will be your starting position.","Step forward with your right leg around 2 feet or so from the foot being left stationary behind and lower your upper body down, while keeping the torso upright and maintaining balance. Inhale as you go down. Note: As in the other exercises, do not allow your knee to go forward beyond your toes as you come down, as this will put undue stress on the knee joint. Make sure that you keep your front shin perpendicular to the ground.","Using mainly the heel of your foot, push up and go back to the starting position as you exhale.","Repeat the movement for the recommended amount of repetitions and then perform with the left leg."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-000000000007", name: "Hip Thrust", nameEs: "Empuje de Cadera", category: "compound", muscleGroups: ["glutes", "hamstrings"], equipment: ["machine", "dumbbell"], notes: "Machine or DB on hips. Squeeze glutes at top.", notesEs: "Con máquina o mancuerna en las caderas. Aprieta los glúteos arriba.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg", instructions: ["Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.","Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.","Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-000000000008", name: "Lat Pulldown", nameEs: "Jalón al Pecho", category: "compound", muscleGroups: ["back", "biceps", "rear_delts"], equipment: ["machine"], notes: "Wide grip. Pull to upper chest.", notesEs: "Agarre amplio. Tira hacia el pecho superior.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg", instructions: ["Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.","Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.","As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.","As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.","After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.","Repeat this motion for the prescribed amount of repetitions."], instructionsEs: [], tags: ["Pull"] },
  { id: "a0000000-0000-4000-8000-000000000009", name: "Leg Press", nameEs: "Prensa de Piernas", category: "compound", muscleGroups: ["quads", "glutes", "hamstrings"], equipment: ["machine"], notes: "Feet shoulder-width. Do not lock knees.", notesEs: "Pies al ancho de hombros. No bloquees las rodillas.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg", instructions: ["Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).","Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.","As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.","Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.","Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-00000000000a", name: "Cable Face Pulls", nameEs: "Tirón Facial con Cable", category: "multi_joint", muscleGroups: ["rear_delts", "upper_back", "rotator_cuff"], equipment: ["cable"], notes: "Pull to face level. External rotation at top.", notesEs: "Tira a nivel de la cara. Rotación externa arriba.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/1.jpg", instructions: ["Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."], instructionsEs: [], tags: ["Pull"] },
  // Isolation / Accessory
  { id: "a0000000-0000-4000-8000-00000000000b", name: "Dumbbell Bicep Curls", nameEs: "Curl de Bíceps con Mancuernas", category: "isolation", muscleGroups: ["biceps"], equipment: ["dumbbell"], notes: "Standing or seated. No swinging.", notesEs: "De pie o sentada. Sin balanceo.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/1.jpg", instructions: ["Stand up straight with a dumbbell in each hand at arm's length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.","Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps. Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a brief pause as you squeeze your biceps.","Then, inhale and slowly begin to lower the dumbbells back to the starting position.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Pull"] },
  { id: "a0000000-0000-4000-8000-00000000000c", name: "Tricep Pushdowns", nameEs: "Extensión de Tríceps en Polea", category: "isolation", muscleGroups: ["triceps"], equipment: ["cable"], notes: "Cable machine. Keep elbows pinned to sides.", notesEs: "Máquina de cable. Mantén los codos pegados al cuerpo.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/1.jpg", instructions: ["Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.","Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.","Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.","After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Push"] },
  { id: "a0000000-0000-4000-8000-00000000000d", name: "Lateral Raises", nameEs: "Elevaciones Laterales", category: "isolation", muscleGroups: ["shoulders"], equipment: ["dumbbell"], notes: "Slight bend in elbows. Raise to shoulder height.", notesEs: "Ligera flexión en los codos. Eleva hasta la altura del hombro.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/1.jpg", instructions: ["Pick a couple of dumbbells and stand with a straight torso and the dumbbells by your side at arms length with the palms of the hand facing you. This will be your starting position.","While maintaining the torso in a stationary position (no swinging), lift the dumbbells to your side with a slight bend on the elbow and the hands slightly tilted forward as if pouring water in a glass. Continue to go up until you arms are parallel to the floor. Exhale as you execute this movement and pause for a second at the top.","Lower the dumbbells back down slowly to the starting position as you inhale.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Push"] },
  { id: "a0000000-0000-4000-8000-00000000000e", name: "Calf Raises", nameEs: "Elevación de Pantorrillas", category: "isolation", muscleGroups: ["calves"], equipment: ["dumbbell", "machine"], notes: "Full range of motion. Pause at top.", notesEs: "Rango completo de movimiento. Pausa arriba.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/1.jpg", instructions: ["Adjust the padded lever of the calf raise machine to fit your height.","Place your shoulders under the pads provided and position your toes facing forward (or using any of the two other positions described at the beginning of the chapter). The balls of your feet should be secured on top of the calf block with the heels extending off it. Push the lever up by extending your hips and knees until your torso is standing erect. The knees should be kept with a slight bend; never locked. Toes should be facing forward, outwards or inwards as described at the beginning of the chapter. This will be your starting position.","Raise your heels as you breathe out by extending your ankles as high as possible and flexing your calf. Ensure that the knee is kept stationary at all times. There should be no bending at any time. Hold the contracted position by a second before you start to go back down.","Go back slowly to the starting position as you breathe in by lowering your heels as you bend the ankles until calves are stretched.","Repeat for the recommended amount of repetitions."], instructionsEs: [], tags: ["Lower"] },
  { id: "a0000000-0000-4000-8000-00000000000f", name: "Plank", nameEs: "Plancha", category: "isolation", muscleGroups: ["core", "shoulders"], equipment: ["bodyweight"], notes: "Hold position. Keep hips level with shoulders.", notesEs: "Mantén la posición. Caderas al nivel de los hombros.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg", instructions: ["Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.","Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."], instructionsEs: [], tags: ["Core"] },
  { id: "a0000000-0000-4000-8000-000000000010", name: "Dead Bug", nameEs: "Bicho Muerto", category: "isolation", muscleGroups: ["core"], equipment: ["bodyweight"], notes: "Opposite arm/leg extension. Press lower back into floor.", notesEs: "Extensión de brazo/pierna opuestos. Presiona la espalda baja contra el suelo.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/1.jpg", instructions: ["Begin lying on your back with your hands extended above you toward the ceiling.","Bring your feet, knees, and hips up to 90 degrees.","Exhale hard to bring your ribcage down and flatten your back onto the floor, rotating your pelvis up and squeezing your glutes. Hold this position throughout the movement. This will be your starting position.","Initiate the exercise by extending one leg, straightening the knee and hip to bring the leg just above the ground.","Maintain the position of your lumbar and pelvis as you perform the movement, as your back is going to want to arch.","Stay tight and return the working leg to the starting position.","Repeat on the opposite side, alternating until the set is complete."], instructionsEs: [], tags: ["Core"] },
  { id: "a0000000-0000-4000-8000-000000000011", name: "Cable Woodchops", nameEs: "Leñador con Cable", category: "multi_joint", muscleGroups: ["core", "obliques"], equipment: ["cable"], notes: "Rotate through core. Control the return.", notesEs: "Rota a través del core. Controla el retorno.", gifUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Cable_Wood_Chop/0.jpg", gifUrl2: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Cable_Wood_Chop/1.jpg", instructions: ["Connect a standard handle to a tower, and move the cable to the highest pulley position.","With your side to the cable, grab the handle with one hand and step away from the tower. You should be approximately arm's length away from the pulley, with the tension of the weight on the cable. Your outstretched arm should be aligned with the cable.","With your feet positioned shoulder width apart, reach upward with your other hand and grab the handle with both hands. Your arms should still be fully extended.","In one motion, pull the handle down and across your body to your front knee while rotating your torso.","Keep your back and arms straight and core tight while you pivot your back foot and bend your knees to get a full range of motion.","Maintain your stance and straight arms. Return to the neutral position in a slow and controlled manner.","Repeat to failure.","Then, reposition and repeat the same series of movements on the opposite side."], instructionsEs: [], tags: ["Core"] },
];

import { EXERCISE_INSTRUCTIONS_ES } from "./exercise-translations-es";

// Populate instructionsEs from the translations file
for (const ex of EXERCISES) {
  ex.instructionsEs = EXERCISE_INSTRUCTIONS_ES[ex.id] ?? [];
}

export const EXERCISE_MAP = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_MAP.get(id);
}

export interface PlanExercise {
  exerciseId: string;
  sets: number;
  reps: number;
  restSeconds: number;
  order: number;
}

export interface WorkoutPlan {
  id: string;
  name: string;
  dayOfWeek: number;
  exercises: PlanExercise[];
}

export const WORKOUT_PLANS: WorkoutPlan[] = [
  {
    id: "b0000000-0000-4000-8000-000000000001",
    name: "Day A — Push Focus",
    dayOfWeek: 1,
    exercises: [
      { exerciseId: "a0000000-0000-4000-8000-000000000001", sets: 3, reps: 10, restSeconds: 150, order: 1 },
      { exerciseId: "a0000000-0000-4000-8000-000000000003", sets: 3, reps: 10, restSeconds: 150, order: 2 },
      { exerciseId: "a0000000-0000-4000-8000-000000000005", sets: 3, reps: 10, restSeconds: 150, order: 3 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000d", sets: 2, reps: 12, restSeconds: 120, order: 4 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000c", sets: 2, reps: 12, restSeconds: 120, order: 5 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000f", sets: 2, reps: 30, restSeconds: 120, order: 6 },
    ],
  },
  {
    id: "b0000000-0000-4000-8000-000000000002",
    name: "Day B — Pull Focus",
    dayOfWeek: 3,
    exercises: [
      { exerciseId: "a0000000-0000-4000-8000-000000000002", sets: 3, reps: 10, restSeconds: 150, order: 1 },
      { exerciseId: "a0000000-0000-4000-8000-000000000008", sets: 3, reps: 10, restSeconds: 150, order: 2 },
      { exerciseId: "a0000000-0000-4000-8000-000000000004", sets: 3, reps: 10, restSeconds: 150, order: 3 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000a", sets: 2, reps: 12, restSeconds: 120, order: 4 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000b", sets: 2, reps: 12, restSeconds: 120, order: 5 },
      { exerciseId: "a0000000-0000-4000-8000-000000000010", sets: 2, reps: 10, restSeconds: 120, order: 6 },
    ],
  },
  {
    id: "b0000000-0000-4000-8000-000000000003",
    name: "Day C — Legs / Full Body",
    dayOfWeek: 5,
    exercises: [
      { exerciseId: "a0000000-0000-4000-8000-000000000009", sets: 3, reps: 10, restSeconds: 150, order: 1 },
      { exerciseId: "a0000000-0000-4000-8000-000000000007", sets: 3, reps: 10, restSeconds: 150, order: 2 },
      { exerciseId: "a0000000-0000-4000-8000-000000000006", sets: 2, reps: 10, restSeconds: 150, order: 3 },
      { exerciseId: "a0000000-0000-4000-8000-000000000011", sets: 2, reps: 12, restSeconds: 120, order: 4 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000e", sets: 2, reps: 15, restSeconds: 120, order: 5 },
      { exerciseId: "a0000000-0000-4000-8000-00000000000f", sets: 2, reps: 30, restSeconds: 120, order: 6 },
    ],
  },
];

export function getPlanByDayOfWeek(dayOfWeek: number): WorkoutPlan | undefined {
  return WORKOUT_PLANS.find((p) => p.dayOfWeek === dayOfWeek);
}
